### ISSUE TITLE
Unable to display full content

### ISSUE THREAD

**Issue by TATyKeFei** [defowler2005/custom-server_form#1]
Hello, I have a problem. This texture pack cannot display the full My server table
![image](https://github.com/defowler2005/custom-server_form/assets/125815900/46abf6cc-b5a0-438b-9996-65874486c0d7)
I made the menu using CrossplatForms in my geyser server working
![image](https://github.com/defowler2005/custom-server_form/assets/125815900/f83046ee-3436-4ee6-a35d-f7c0a8d79f3b)
But somehow, this ui doesn't display everything, the original ui can display completely
Please help me! Thank you!

**Comment by defowler2005** [comment]
Woah, I had no idea people would actually use this, Could you add me on discord so I can assist further? (I have no ecxperience with geyser

**Comment by TATyKeFei** [comment]
> 哇，我不知道人们真的会使用它，你能在 discord 上添加我，以便我可以进一步提供帮助吗？（我对间歇泉没有经验

Ok, how can I add you

**Comment by defowler2005** [comment]
> > 哇，我不知道人们真的会使用它，你能在 discord 上添加我，以便我可以进一步提供帮助吗？（我对间歇泉没有经验
> 
> Ok, how can I add you
defowler2005 is the username but a minecraft picture
